#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-orc
Version  : 1.5.2
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/orc/orc-shims/1.5.2/orc-shims-1.5.2.jar
Source0  : https://repo1.maven.org/maven2/org/apache/orc/orc-shims/1.5.2/orc-shims-1.5.2.jar
Source1  : https://repo1.maven.org/maven2/org/apache/orc/orc-shims/1.5.2/orc-shims-1.5.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-orc-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-orc package.
Group: Data

%description data
data components for the mvn-orc package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/orc/orc-shims/1.5.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/orc/orc-shims/1.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/orc/orc-shims/1.5.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/orc/orc-shims/1.5.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/orc/orc-shims/1.5.2/orc-shims-1.5.2.jar
/usr/share/java/.m2/repository/org/apache/orc/orc-shims/1.5.2/orc-shims-1.5.2.pom
